@startuml
!theme cerulean
'https://plantuml.com/component-diagram

title Application Diagram

node "App Module" {
  [UI]
  [Data]
  [Room]
}

package "UI" {
    [ViewModels]
    [Components]
    [Theme]
}

package "Data" {
    [Repositories]
    [Storage]
}

database "Room" {
    folder "App Database" {
       [Comics]
    }
}

[ViewModels] --> [Repositories]
[Repositories] --> [Storage]
[Repositories] --> [Api Module]

[Storage] --> "Room"

node "Api Module" {
   [MarvelSDK]
}

cloud {
   [Marvel Rest API]
}

"Api Module" -> [Marvel Rest API]
@enduml